# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkppLkjuGkcJGRG_U3mWebmIH2SHb6DL
"""

import math
from collections import Counter

def mostCommonLabel(knn):
    counts = {}
    for label in knn:
        if label in counts:
            counts[label] += 1
        else:
            counts[label] = 1

    most_common = None
    max_count = -1

    for label, count in counts.items():
        if count > max_count:
            most_common = label
            max_count = count

    return most_common

def Distance(x1, x2):
    dist = 0
    for i in range(len(x1)):
        dist += (x1[i] - x2[i]) ** 2
    return dist**0.5

def meanSquaredError(y_true, y_pred):
    return sum((y_true[i] - y_pred[i])**2 for i in range(len(y_true))) / len(y_true)

"""KNN For logitic regression"""

def predictLabel(X_train, y_train, X_test, k):
    preds = []

    for x_test in X_test:
        distances = []
        for i in range(len(X_train)):
            dist = Distance(X_train[i], x_test)
            distances.append((dist, y_train[i]))

        distances.sort(key=lambda pair: pair[0])
        k_neighbors = [label for (_, label) in distances[:k]]

        mc = mostCommonLabel(k_neighbors)

        preds.append(mc)

    return preds

X_train = [[1.0, 2.0],[1.5, 1.8],[5.0, 8.0],[8.0, 8.0],[1.0, 0.6],[9.0, 11.0],]
y_train = [0, 0, 1, 1, 0, 1]

X_test = [[1.2, 1.9],[8.5, 9.0],[4.0, 5.0]]

k = 2

predictions = predictLabel(X_train, y_train, X_test, k)
print("Predictions:", predictions)

"""KNN for Linear Regression"""

def predictLinear(X_train, y_train, X_test, k):
    preds = []

    for x_test in X_test:
        distances = []
        for i in range(len(X_train)):
            dist = Distance(X_train[i], x_test)
            distances.append((dist, y_train[i]))

        distances.sort(key=lambda pair: pair[0])
        k_neighbors = [value for (_, value) in distances[:k]]

        avg_value = sum(k_neighbors) / len(k_neighbors)

        preds.append(avg_value)

    return preds

X_train = [[1,2],[2,3],[3,4],[4,5],[5,6]]
y_train = [2.1, 2.9, 4.2, 5.0, 6.1]

# New points we want to predict
X_test = [[1.5,2.5],[3.5,4],[5.0,3.5]]

k = 2

predictions = predictLinear(X_train, y_train, X_test, k)
print("Predictions:", predictions)

newPredictions = predictLinear(X_train,y_train,X_train,k)

error = meanSquaredError(y_train,newPredictions)

print("Error: ",error)