# -*- coding: utf-8 -*-
"""Lin_Reg_Model_Nexus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vu_DjixV8yyWgHi3zQSxTP4xvOmfZMT

Linear Regression Model
"""

def dotProduct(w,x):
  sum = 0
  for i in range(len(w)):
    sum+=w[i]*x[i]
  return sum

def gradientDescent(X, y, alpha,n):

    samples = len(X)
    features = len(X[0])

    w = [0.0 for _ in range(features)]
    b = 0.0

    for epoch in range(n):
        dw = [0.0 for _ in range(features)]
        db = 0.0

        for i in range(samples):
            y_pred = dotProduct(w, X[i]) + b
            error = y_pred - y[i]
            for j in range(features):
                dw[j] += error * X[i][j]
            db += error
        dw = [d / samples for d in dw]
        db /= samples

        for j in range(features):
            w[j] -= alpha * dw[j]
        b -= alpha * db

        if epoch % 250 == 0:
            mse = sum((dotProduct(w, X[i]) + b - y[i])**2 for i in range(samples)) /samples
            print(f"Iteration {epoch}: Error = {mse:.4f}")

    return w, b

"""Using a random small sample set to train and test the model"""

x = [[1, 2],[2, 3],[3, 4],[4, 5]]
y = [5, 7, 9, 12]
alpha = 0.01
n = 5000
w, b = gradientDescent(x, y, alpha, n)
print("\nFinal weights:", w)
print("Final bias:", b)
# Predict new data
x_test = [[1, 2],[2, 3],[3, 4],[4, 5]]
predictions = []
for i in x_test:
  prediction = dotProduct(i,w);
  prediction+=b;
  print("\nPredictions:", prediction)
  predictions.append(prediction)
errors = []
for i in range(len(y)):
  if y[i] != 0:
    err = abs(y[i] - predictions[i]) / abs(y[i]) * 100
    errors.append(err)
  else:
    errors.append(0)
avg = 0
for i in errors:
  avg+=i
avg = avg/len(errors)
print("Error percentage: ",avg)