# -*- coding: utf-8 -*-
"""Log_Reg_Nexus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cepbxOzd1kFhvYF_KmGNP0o0te5CQV8a

Logistic Regression
"""

def dotProduct(w,x):
  sum = 0
  for i in range(len(w)):
    sum+=w[i]*x[i]
  return sum

def sigmoid(z):
  e = 2.71828
  return (1/(1+e**(-z)))

import math
def gradientDescent(X, y, alpha,n):

    samples = len(X)
    features = len(X[0])

    w = [0.0 for _ in range(features)]
    b = 0.0

    for epoch in range(n):
        dw = [0.0 for _ in range(features)]
        db = 0.0
        loss = 0
        for i in range(samples):
            z = dotProduct(w, X[i]) + b
            y_pred = sigmoid(z)
            error = y_pred - y[i]
            for j in range(features):
                dw[j] += error * X[i][j]
            db += error
            loss += -(y[i]*math.log(y_pred + 1e-9) + (1 - y[i])*math.log(1 - y_pred + 1e-9))
            loss /= samples
        if(epoch%250==0):
          print(f"Iteration {epoch}: Loss = {loss:.4f}")
        dw = [d / samples for d in dw]
        db /= samples

        for j in range(features):
            w[j] -= alpha * dw[j]
        b -= alpha * db

    return w, b

x = [[5,2],[3,3],[2,8],[1,1],[6,3],[5,5],[8,3],[10,10]]
y = [0, 1, 0, 1, 0, 1, 0, 1]
alpha = 0.1
n = 5000

w, b = gradientDescent(x, y, alpha, n)

print("\nFinal weights:", w)
print("Final bias:", b)

prediction = []
threshold = 0.5

x_test = [[1,2],[1,1],[5,3],[2,2],[5,5]]

for i in x_test:
  z = dotProduct(w, i) + b
  y_pred = sigmoid(z)
  prediction.append(1 if y_pred >= threshold else 0)
print("Predictions:", prediction)